version: 2.1

jobs:
  run_node_starter:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm deps
          command: |
            npm install --save
      - run:
          name: ssh into remote server 
          command: |
          
            cd ./etc
            mkdir custom_ci_path
workflows:
  build_node_api:
    jobs:
      - run_node_starter
