version: 2.1

jobs:
  run_node_starter:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm deps
          command: |
            npm install --save
      - run:
          name: Build API
          command: npm run build
workflows:
  build_node_api:
    jobs:
      - run_node_starter
